front-end/package-lock.json
front-end/src/components/ProfileNavbar.js
front-end/src/components/ProfilePage.css
front-end/src/components/ProfilePage.js

I did not yet link the edit profile page however, I added profile page with a header that allows the user to logout or create a group (assumes the user is already logged in).

Created a profile page with a custom header

---

front-end/src/App.js

Inserted routes to the profile page, edit profile page, and edit image in App.js

Added routes

---

front-end/src/components/EditProfilePage.js
front-end/src/components/ProfilePage.css
front-end/src/components/ProfilePage.js

I changed the page styling for the profile page and edit profile page
Changes:
- removed footers
- added padding

Update to page styling

---

front-end/src/components/EditProfilePage.js
front-end/src/components/ProfilePage.js

Put up the mock image link from Picsum for the profile image

Updated mock image using Picsum

---

front-end/src/components/EditImage.js
front-end/src/components/EditProfilePage.js
front-end/src/components/ProfileNavbar.js
front-end/src/components/ProfilePage.css
front-end/src/components/ProfilePage.js

Updated routes 
Added the footers
Changed one style element in the edit image page

Updates to profile pages

---

front-end/src/components/ProfileNavbar.js

Made updates to the profile navbar

Added the profile icon and updated login link

---

front-end/src/components/group.css
front-end/src/components/group.js

**Finalized format and CSS**
- Made Focus outline of theme color
- Updated font family for input fields
- Updated Labels to a placeholder in the form fields
- Updated the positioning for all the fields
- Added user name field
- Redirected submit for back to explore page
- Fixed CSS
- Added new buttons
- Fixed the focus outline issue and aligned the slider with the dollar input field. (Evened out the spacing)

Create group new

---

front-end/package-lock.json
front-end/package.json
front-end/src/components/Login.js
front-end/src/components/Register.js
front-end/src/components/footer.css
front-end/src/components/footer.js
front-end/src/index.js

- replaces mdb buttons with semantic ui buttons
- created footer.css to fix padding issues with login page

Fixes to login and register buttons

---

back-end/app.js

Created a routing method to get profile data from mockaroo

Added a routing method for the profile page

---

back-end/app.js
back-end/routes/editProfilePage
back-end/routes/profilePage.js

Added editProfilePage routing file
Added profilePage routing file (moved from app.js)

Added route methods for profile and edit pages

---

front-end/src/pages/EditImage.js
front-end/src/pages/EditProfilePage.js
front-end/src/pages/ProfilePage.js

Edited the frontend EditProfilePage, ProfilePage, and EditImage js files to connect to the server

Connect profile related files to back-end server

---

back-end/app.js
back-end/routes/search.js
front-end/package-lock.json
front-end/src/components/searchbar.js
front-end/src/pages/explore.js
front-end/yarn.lock

Linked search front-end to back-end
Fixed minor bug in route

Completed seach Backend

---

back-end/test/editImageTest.js
front-end/src/pages/EditImage.js
front-end/src/pages/EditProfilePage.js
front-end/src/pages/ProfilePage.js

Changed the urls (uses the env values)
Changed a describe header in the editImage unit test file

Change urls front end profile related pages

---

back-end/package-lock.json
back-end/routes/search.js
back-end/test/searchTest.js
front-end/src/components/searchbar.js

Unit testing:
- Checks status code
- Checks if content type is json
- Checks if res.body is object

Unit testing for searchbar

---

back-end/models/Group.js
back-end/models/User.js
back-end/routes/index.js
front-end/src/components/filter.js
front-end/src/components/group.js

Created schema for Explore and user

---

back-end/models/Group.js
back-end/package-lock.json
back-end/routes/search.js
front-end/package-lock.json
front-end/src/App.css
front-end/src/components/card.js
front-end/src/components/searchbar.js
front-end/src/pages/explore.js
front-end/yarn.lock

- Added total results counter in explore page
- Completed search backend
- Removed case sensitivity

Completed search backend & fixed schema

---

back-end/package-lock.json
back-end/routes/index.js
back-end/routes/search.js
front-end/package-lock.json
front-end/package.json
front-end/src/components/searchbar.js
front-end/src/pages/explore.js
front-end/yarn.lock

- Added page query param
- Added .skip(), .limit() in getting data from MongoDB
- Added count

Added Infinite scrolling in explore page

---

back-end/routes/editImage.js
back-end/routes/editProfilePage.js
back-end/routes/profilePage.js
front-end/src/components/ProfileNavbar.js
front-end/src/pages/EditImage.js
front-end/src/pages/EditProfilePage.js
front-end/src/pages/ProfilePage.js

Updated the editProfilePage and editImage pages with the database integration and also using jwt tokens
They do not function yet (waiting on jwt configurations/authentication to be set up)
Also made minor changes to the profile page related code
Update the profileNavbar so that when the user logs out, the token is removed

User story/24/tasks/111/112/113/connect database and update edit image and edit profile page

---

back-end/app.js
back-end/middleware_auth/signup_auth.js
back-end/signing.control.js
front-end/src/components/Login.js
front-end/src/components/Register.js

- jwt token saved as a cookie after sign in and sign up
- CORS policy needed to be written to accept creditentials in axios post

JWT token finalized

---

back-end/test/editImageTest.js
back-end/test/editProfilePageTest.js
back-end/test/profilePageTest.js

Updated each test with a commented section for when the authorization is set
Updated the tests based on the new User schema (based on what the API will return)

update profile related unit tests

---

back-end/package-lock.json
back-end/routes/search.js
front-end/package.json
front-end/src/components/footer.js
front-end/src/components/searchbar.js
front-end/src/pages/explore.js
front-end/yarn.lock

- Used useStateRef to account for states not being changed immediately
- Solved issues related to edge cases in search

Fixed a few bugs related to the search and explore page

---

back-end/routes/auth_routes.js
back-end/signing.control.js
front-end/src/components/Login.js
front-end/src/components/Register.js
front-end/src/components/navbar.js

- Duplicate email error in registering now shows in frontend
- Navbar switches based on if a user is signed in or not

Duplicate email error and Navbar switch

---

back-end/routes/createGroup.js

Fetch images from cloudinary to be used in cards thumbnail after group creation

Added cloudinary to store/fetch imgs

---

front-end/src/App.css
front-end/src/pages/explore.js

Added alerts and error pages

---

.circleci/config.yml
back-end/Dockerfile
front-end/Dockerfile

Updated config.yml with export CI=false and changed the cd back-end to front-end
Also added dockerfiles

Updates to CI config

---

.circleci/config.yml

Undo changes to configuration
